apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: cloudforge-dev
  namespace: argocd

spec:
  project: default

  source:
    repoURL: https://github.com/aryans1319/cloudforge-demo-app.git
    targetRevision: main
    path: k8s/overlays/dev

  destination:
    server: https://kubernetes.default.svc
    namespace: dev

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true