apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: dev

replicas:
  - name: cloudforge-demo
    count: 1

patches:
  - path: ingress-patch.yaml

images:
  - name: ghcr.io/aryans1319/cloudforge-demo-app
    newTag: "c481dcb758a08490e10646dc92561360c60370da"